### ISSUE TITLE
Does not handle re-run/move

### ISSUE THREAD

**Issue by andyleejordan** [jeffaco/msft-updatedns#4]
I ran `./updatedns.sh --configure -v` which put an entry in my crontab, but then I moved the `msft-updatedns` folder and re-ran it. Instead of updating (i.e. deleting and replacing) the previous entry, it just added a second entry. Since the first entry was invalid, cron emailed me failures.

**Comment by jeffaco** [comment]
@andschwa Yeah, this would happen.

Before you move it, you should unregister it. Or you could just edit your crontab to fix it. Or delete your crontab entirely, then reconfigure.

The issue here is that I'm changing crontab via shell, and I want to be REALLY sure that I'm dealing with the proper lines. I can certainly change updatedns to be less "stringent" here, but then I run the risk of deleting lines that the end-user really wanted in crontab. For example, what if the user had something else called updatedns, in another path, to update some alternate DNS server or something?

I'm open to suggestions here. What are your thoughts?

**Comment by jeffaco** [comment]
@andschwa What are your thoughts to my comments on this issue?

**Comment by andyleejordan** [comment]
Eh I lean toward anything mentioning updatedns is owned by updatedns. You could be really careful and add a unique identifier if you want but probably not necessary for our use cases.
